#! /usr/bin/env python3

from pyfiglet import Figlet
import click
from random import randint
from pathlib import Path 

from utils import CellularAutomata, render_halfblock, save_evolution

f = Figlet(font="smslant")


banner = f.renderText("CellularAutomata")


@click.command()
@click.option(
    "-ic", "--initial-configuration", type=int, help="Seed for starting configuration"
)
@click.option("-r", "--rule", type=int, help="Local update rule number")
@click.option(
    "-n",
    "--neighbourhood",
    type=int,
    default=1,
    help="Neighbourhood radius (default: 1).",
)
@click.option(
    "-w", "--width", type=int, default=30, help="Lattice width (default: 30)."
)
@click.option(
    "-t",
    "--timesteps",
    type=int,
    default=20,
    help="Number of time steps (default: 20).",
)
@click.option(
    "-s",
    "--states",
    type=int,
    default=2,
    help="Number of states each cell can have (default: 2)",
)
@click.option(
    "--display/--nodisplay",
    default=True,
    help="Toggle display of the cellular automaton (default: display).",
)
@click.option(
   "-ct",
   "--configuration-timestep",
   type=int,
   help="Display the configuration of a specific timestep"
)
@click.option(
   "-cc",
   "--cell-change",
   type=int,
   help="Display the states of a cell over time"
)
@click.option(
   "-o",
   "--output",
   type=Path,
   help="Path to save evolution"
)
def cellular_automata(
    initial_configuration: int | None,
    rule: int | None,
    neighbourhood: int,
    width: int,
    timesteps: int,
    states: int,
    display:bool,
    configuration_timestep:int|None,
    cell_change:int|None,
    output:Path
) -> None:
    if display:
      click.secho(banner, fg="green", bold=True)
      click.echo("Welcome to the Cellular Automata CLI 🚀")

      click.echo(click.style("Running with parameters:", bold=True))
      click.echo(f"  Neighbourhood radius: {neighbourhood}")
      click.echo(f"  Lattice width: {width}")
      click.echo(f"  Time steps: {timesteps}")
      click.echo(f"  Cell states: {states}")

    ca = CellularAutomata(
        cell_states=states,
        neighbourhood_radius=neighbourhood,
        lattice_width=width,
        time_steps=timesteps,
        initial_state=initial_configuration,
        transition_rule_number=rule,
    )
    
    if display:
      click.echo(f"  Initial configuration: {ca.info.lattice_evolution[0]}")
      click.echo(f"  Rule: {ca.info.local_transition_rule}")

      click.echo(render_halfblock(values=ca.evolution))

    if configuration_timestep is not None:
      click.echo(" ".join(map(str, ca.evolution[configuration_timestep])))
    elif cell_change is not None:
      click.echo(" ".join(map(str, ca.evolution[:,cell_change])))
    if output:
      save_evolution(values=ca.evolution, path=output)
      click.echo(f"Saved to {output}")
if __name__ == "__main__":
    cellular_automata()
